services:
  db:
    image: postgres:15
    container_name: db-marketplace
    env_file: src/.env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    env_file: src/.env
    container_name: marketplace_app
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]
    ports:
      - "9999:8000"
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
